const TOGGLE_THEME = 'TOGGLE_THEME';
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
const SET_MAX_PAGES = 'SET_MAX_PAGE';
export { TOGGLE_THEME, TOGGLE_SIDEBAR, SET_CURRENT_PAGE, SET_MAX_PAGES };
